# Generated by Django 4.2.11 on 2024-03-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Xomashyo nomi:')),
                ('qty', models.IntegerField(verbose_name=' Foydalanilgan xomashyolar soni:')),
                ('price', models.IntegerField(verbose_name='Xomashyo narxi:')),
            ],
            options={
                'verbose_name': 'Xomashyo_',
            },
        ),
    ]
