# Generated by Django 4.2.11 on 2024-03-11 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_material'),
        ('task', '0004_remove_promaterial_material_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
