# Generated by Django 4.2.11 on 2024-03-10 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_product_pro_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promaterial',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pros_id', to='task.product'),
        ),
    ]
