# Generated by Django 4.2.11 on 2024-03-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_material'),
        ('task', '0003_alter_promaterial_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promaterial',
            name='material_id',
        ),
        migrations.AlterField(
            model_name='promaterial',
            name='quantity',
            field=models.IntegerField(verbose_name=' Foydalanilgan xomashyolar soni:'),
        ),
        migrations.AddField(
            model_name='promaterial',
            name='material_id',
            field=models.ManyToManyField(related_name='mat_id', to='category.material'),
        ),
    ]
